//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksShoppingCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
        }
    
        public int Id { get; set; }
        public string AspNetUser_Id { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddress { get; set; }
        public decimal TotalPrice { get; set; }
        public System.DateTime BuyDT { get; set; }
        public string Memo { get; set; }
    
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
